def echec():
    raise Exception()






try:
    echec()
except:
    print("ok")